SELECT DISTINCT ?this ?label ?comment
WHERE {
    ?this a owl:Ontology;
    OPTIONAL {
        ?this rdfs:label  ?label.
    }
    OPTIONAL {
        ?this dc:title ?label.
    }
    OPTIONAL {
        ?this dcterms:title ?label.
    }
    OPTIONAL {
        ?this rdfs:comment  ?comment.
    }
}