SELECT DISTINCT ?this ?label ?x ?y ?z ?rx ?ry ?rz ?zx ?zy ?zz ?template
WHERE {
    ?this
        rdfs:label ?label;
        ux:position ?coords;
    .
    ?coords
        ux:x ?x;
        ux:y ?y;
    .
    OPTIONAL { ?this ux:z ?z }
}