SELECT DISTINCT ?this ?label ?comment
WHERE {
    ?this a owl:Ontology;
    OPTIONAL {
        ?this rdfs:label  ?title1.
    }
    OPTIONAL {
        ?this dc:title ?title2.
    }
    OPTIONAL {
        ?this dcterms:title ?title3.
    }
    OPTIONAL {
        ?this rdfs:comment  ?comment.
    }
    BIND(coalesce(?title1, ?title2, ?title3) AS ?label)
}