SELECT DISTINCT ?that ?this ?label ?comment ?range WHERE {
    {	?this	rdfs:domain ?that;
                rdfs:label ?label;
                rdfs:range ?range.
        OPTIONAL { ?this rdfs:comment ?comment. }
    } UNION {
        ?that    rdfs:subClassOf ?super.
        ?this	rdfs:domain ?super;
                rdfs:label ?label;
                rdfs:range ?range.
        OPTIONAL { ?this rdfs:comment ?comment. }
    }
}
ORDER BY ?that ?label
BINDINGS ?that { (<{{this}}>) }
