#
# User Application
#
SELECT DISTINCT ?this ?id ?label ?comment ?core WHERE {
	?this	a               iq:Application;
            iq:id           ?id;
		    rdfs:label	    ?label;
            Scorpio4       ?core;
    OPTIONAL {
        ?this            rdfs:comment    ?comment;
    }
} BINDINGS ?this { (<{{application}}>) }
